name: build
on: [push]

jobs:
  tests:
    strategy:
      matrix:
        go-version: [1.11.x, 1.12.x, 1.13.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]  
    name: tests
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - run: |
          go test -v -race -cover
  coverage:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]  
    name: coverage
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - run: |
          go test -v -race -cover -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload coverage to Codecov  
        uses: codecov/codecov-action@v1.0.4
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella 
