name: build
on: [push]

jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest]
    name: golangci-lint
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - run: |
          docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.24.0 golangci-lint run -v   
  tests:
    strategy:
      matrix:
        go-version: [1.11.x, 1.12.x, 1.13.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]  
    name: tests
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - run: |
          go test -v -race -cover
  coverage:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest]  
    name: coverage
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - run: |
          go test -v -race -cover -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload coverage to Codecov  
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella 
